"""Generate `tplink_modern/endpoints.py` from the verified survey reports.

The constants table is the machine-readable half of docs/router-api-inventory.md, so it is
generated rather than typed: the module/form set comes from the bundle scan, the status from the
read-only live probe, and row field names from responses the router actually returned. Re-running
this after a fresh scan regenerates the table; a test keeps the doc's counts honest.

    venv/Scripts/python.exe -m tools.inventory.gen_endpoints \
        --inventory .cache/ax12-ui/inventory-v2.json --probe .cache/ax12-ui/live-probe.json
"""

from __future__ import annotations

import argparse
import json
import textwrap
from typing import Any

from tools.inventory.probe_live import verdict_category

HEADER = '''"""Every Archer AX12 endpoint the survey found, with what this firmware does about it.

Generated by `tools/inventory/gen_endpoints.py` -- do not edit by hand. Two sources:
`tools/inventory/extract_ui_inventory.py` (the router's own web bundles, which says what the UI
can ask for) and `tools/inventory/probe_live.py` (read/load/list requests to AX12v1_1.10.2, which
says what this firmware answers). `ui_operations` lists verbs seen in the bundles, including
writes, and is evidence of intent only -- none of them were sent by this survey.

This is the single source of truth for `docs/router-api-inventory.md`; the test
`tests/test_endpoints_inventory.py` fails if the two disagree.
"""

from __future__ import annotations

from dataclasses import dataclass

# The firmware answers this form with a read, load or list request.
ANSWERED = "answered"
# Every approved verb came back `no such callback`: this firmware has no handler for the form.
NOT_IMPLEMENTED = "not-implemented"
# The handler exists but refused a parameterless read (`invalid proto_name`, `invalid parameter
# vpntype`), so it is reachable once the right argument is supplied.
NEEDS_PARAMETERS = "exists-needs-parameters"
# The CGI answered with a file or a server error instead of the JSON envelope.
NON_JSON = "non-json-or-server-error"
# The router served HTTP 404 for this module: the UI references it, this device does not host it.
NOT_SERVED = "not-served-404"
# Deliberately not probed: the form name is itself an action (`reboot`, `logout`, `cloud_upgrade`).
NOT_PROBED = "not-probed"
# The router answered `{"success": false}` with no error field at all, so neither a missing handler
# nor a missing argument can be attributed to it.
REFUSED_NO_REASON = "refused-without-reason"
# The router named a condition (`err_download`, `recovery enable is off`) rather than a missing
# argument, so the form is reachable only once that condition changes.
REFUSED_WITH_REASON = "refused-stated-reason"

READ_VERBS = ("read", "load", "list")


@dataclass(frozen=True)
class Endpoint:
    """One `module?form=` pair, as the UI builds it and as this firmware answered it."""

    module: str
    form: str
    ui_operations: tuple[str, ...]
    read_verbs: tuple[str, ...] = ()
    status: str = NOT_PROBED
    others_key: str | None = None
    row_fields: tuple[str, ...] = ()
    #: False when no bundle names this form and only this package addresses it.
    in_bundles: bool = True

    @property
    def url(self) -> str:
        """The path the SDK passes to `ArcherAX12.read`/`write`/`api`."""
        return f"{self.module}?form={self.form}"

    @property
    def is_row_form(self) -> bool:
        """True when the form is a list of records rather than a settings blob.

        Empty tables answer `{}`, not `[]`, so a row form has to be recognised from its `others`
        sibling as well as from an array payload.
        """
        return bool(self.row_fields) or self.others_key is not None


def _e(module: str, form: str, ui: tuple[str, ...], read: tuple[str, ...], status: str,
       others: str | None = None, fields: tuple[str, ...] = (), in_bundles: bool = True) -> Endpoint:
    return Endpoint(module, form, ui, read, status, others, fields, in_bundles)


ENDPOINTS: tuple[Endpoint, ...] = (
'''

FOOTER = ''')

#: Every form under a module, e.g. ``MODULES["admin/nat"]``.
MODULES: dict[str, tuple[str, ...]] = {
    _module: tuple(sorted(_names))
    for _module, _names in (
        (_module, {endpoint.form for endpoint in ENDPOINTS if endpoint.module == _module})
        for _module in sorted({endpoint.module for endpoint in ENDPOINTS})
    )
}

#: `module?form=x` -> endpoint, for call sites that already hold a URL string.
BY_URL: dict[str, Endpoint] = {endpoint.url: endpoint for endpoint in ENDPOINTS}

MODULE_COUNT = len(MODULES)
FORM_COUNT = len(ENDPOINTS)
ANSWERED_COUNT = sum(1 for endpoint in ENDPOINTS if endpoint.status == ANSWERED)


def endpoint(module: str, form: str) -> Endpoint | None:
    """Look one endpoint up by module and form, with or without a leading slash."""
    return BY_URL.get(f"{module.lstrip('/')}?form={form.lstrip('/')}")


def forms(module: str) -> tuple[str, ...]:
    """Every inventoried form on a module."""
    return MODULES.get(module.lstrip("/"), ())


def answered_forms(module: str) -> tuple[str, ...]:
    """Forms this firmware actually answers with read, load or list."""
    return tuple(
        name
        for name in forms(module)
        if (entry := endpoint(module, name)) is not None and entry.status == ANSWERED
    )
'''


def item_fields(schema: dict[str, Any] | None) -> tuple[str, ...]:
    """Row field names from an answered list payload, empty when the table had no rows here."""
    if not schema:
        return ()
    if schema.get("type") == "array":
        item = schema.get("item") or {}
        return tuple(sorted(item.get("keys", {})))
    return ()


def others_key(schema: dict[str, Any] | None) -> str | None:
    if not schema:
        return None
    keys = schema.get("keys") or {}
    if isinstance(keys, dict) and keys:
        return ",".join(sorted(keys))
    return None


def literal(value: tuple[str, ...]) -> str:
    if not value:
        return "()"
    inner = ", ".join(repr(item) for item in value)
    return f"({inner},)" if len(value) == 1 else f"({inner})"


STATUS_NAME = {
    "answered": "ANSWERED",
    "not-implemented": "NOT_IMPLEMENTED",
    "exists-needs-parameters": "NEEDS_PARAMETERS",
    "non-json-or-server-error": "NON_JSON",
    "not-served-404": "NOT_SERVED",
    "not-probed": "NOT_PROBED",
    "refused-without-reason": "REFUSED_NO_REASON",
    "refused-stated-reason": "REFUSED_WITH_REASON",
}


def entry_for(record: dict[str, Any] | None) -> tuple[str, tuple[str, ...], str | None, tuple[str, ...]]:
    """`(status, answered_with, others_key, row_fields)` for one probed form."""
    if record is None:
        return "not-probed", (), None, ()
    others: str | None = None
    fields: tuple[str, ...] = ()
    for view in record["schema_by_operation"].values():
        fields = fields or item_fields(view.get("data"))
        others = others or others_key(view.get("others"))
    return verdict_category(record), tuple(record["answered_by"]), others, fields


def merged_modules(inventory: dict[str, Any], probe: dict[str, Any]) -> dict[str, dict[str, tuple[dict[str, Any], bool]]]:
    """Bundle forms plus any form only this SDK addresses.

    `admin/wireless?form=statistics` answers on this firmware but appears in no bundle; leaving it
    out would mean the table cannot vouch for a call site the package actually ships. Each entry
    carries whether the bundles named it, because "no verb recorded" and "not in the bundles" are
    different facts -- eighteen bundle forms have no attributable call site.
    """
    modules: dict[str, dict[str, tuple[dict[str, Any], bool]]] = {
        module: {form: (info, True) for form, info in forms.items()}
        for module, forms in inventory["modules"].items()
    }
    known = {(module, form) for module, forms in modules.items() for form in forms}
    for record in probe["probes"]:
        key = (record["module"], record["form"])
        if key in known:
            continue
        modules.setdefault(record["module"], {})[record["form"]] = ({"operations": ["not observed"]}, False)
    return modules


def render_entry(module: str, form: str, ui: tuple[str, ...], read: tuple[str, ...], status: str,
                 others: str | None, fields: tuple[str, ...], in_bundles: bool = True) -> str:
    args = [f'"{module}"', f'"{form}"', literal(ui), literal(read), STATUS_NAME[status]]
    if others:
        args.append(f"others={others!r}")
    if fields:
        args.append(f"fields={literal(fields)}")
    if not in_bundles:
        args.append("in_bundles=False")
    one_line = "    _e(" + ", ".join(args) + "),"
    if len(one_line) <= 118:
        return one_line
    wrapped = textwrap.fill(
        ", ".join(args[2:]), width=104, initial_indent=" " * 8, subsequent_indent=" " * 25
    )
    return f'    _e("{module}", "{form}",\n{wrapped}),'


def render(inventory: dict[str, Any], probe: dict[str, Any]) -> str:
    verdicts = {f"{p['module']}?form={p['form']}": p for p in probe["probes"]}
    modules = merged_modules(inventory, probe)
    lines: list[str] = [HEADER.rstrip("\n")]
    for index, module in enumerate(sorted(modules)):
        if index:
            lines.append("")
        lines.append(f"    # /{module}")
        for form in sorted(modules[module]):
            info, in_bundles = modules[module][form]
            ui = tuple(op for op in info["operations"] if op != "not observed")
            status, read, others, fields = entry_for(verdicts.get(f"{module}?form={form}"))
            lines.append(render_entry(module, form, ui, read, status, others, fields, in_bundles))
    return "\n".join(lines) + "\n" + FOOTER


def render_markdown(inventory: dict[str, Any], probe: dict[str, Any], patterns: list[dict[str, Any]]) -> str:
    """The doc's module reference, generated so prose and table cannot disagree.

    One row per form: the verbs the UI bundles apply to it, and what this firmware did when asked
    with read, load or list.
    """
    verdicts = {f"{p['module']}?form={p['form']}": p for p in probe["probes"]}
    modules = merged_modules(inventory, probe)
    status_label = {
        "answered": "answered",
        "not-implemented": "no such callback",
        "exists-needs-parameters": "needs a parameter",
        "non-json-or-server-error": "not JSON",
        "not-served-404": "HTTP 404",
        "not-probed": "not probed",
        "refused-without-reason": "declined, no reason",
        "refused-stated-reason": "declined: stated reason",
    }
    lines = [
        "| Module | Form | Verbs in the UI | This firmware |",
        "| --- | --- | --- | --- |",
    ]
    for module in sorted(modules):
        for form in sorted(modules[module]):
            record = verdicts.get(f"{module}?form={form}")
            info, in_bundles = modules[module][form]
            ui = ", ".join(op for op in info["operations"] if op != "not observed") or "-"
            if not in_bundles:
                ui = "not in the bundles"
            if record is None:
                outcome = "not probed"
            else:
                outcome = status_label[verdict_category(record)]
                if verdict_category(record) == "answered":
                    outcome += f" ({'+'.join(record['answered_by'])})"
            lines.append(f"| `/{module}` | `{form}` | {ui} | {outcome} |")
    if patterns:
        lines.append("")
        lines.append("Built at runtime, so no single form name is readable statically:")
        for pattern in patterns:
            lines.append(f"- `{pattern['url']}` in `{pattern['chunk']}`")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inventory", default=".cache/ax12-ui/inventory-v2.json")
    parser.add_argument("--probe", default=".cache/ax12-ui/live-probe.json")
    parser.add_argument("--out", default="tplink_modern/endpoints.py")
    parser.add_argument("--markdown", default="", help="also write the doc's module reference table here")
    args = parser.parse_args()

    with open(args.inventory, encoding="utf-8") as handle:
        inventory = json.load(handle)
    with open(args.probe, encoding="utf-8") as handle:
        probe = json.load(handle)

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(render(inventory, probe))

    if args.markdown:
        with open(args.markdown, "w", encoding="utf-8") as handle:
            handle.write(render_markdown(inventory, probe, inventory.get("dynamic_patterns", [])))

    merged = merged_modules(inventory, probe)
    forms = sum(len(entry) for entry in merged.values())
    answered = sum(1 for p in probe["probes"] if verdict_category(p) == "answered")
    print(f"wrote {args.out}: {len(merged)} modules, {forms} forms, {answered} answered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
