"""Every Archer AX12 endpoint the survey found, with what this firmware does about it.

Generated by `tools/inventory/gen_endpoints.py` -- do not edit by hand. Two sources:
`tools/inventory/extract_ui_inventory.py` (the router's own web bundles, which says what the UI
can ask for) and `tools/inventory/probe_live.py` (read/load/list requests to AX12v1_1.10.2, which
says what this firmware answers). `ui_operations` lists verbs seen in the bundles, including
writes, and is evidence of intent only -- none of them were sent by this survey.

This is the single source of truth for `docs/router-api-inventory.md`; the test
`tests/test_endpoints_inventory.py` fails if the two disagree.
"""

from __future__ import annotations

from dataclasses import dataclass

# The firmware answers this form with a read, load or list request.
ANSWERED = "answered"
# Every approved verb came back `no such callback`: this firmware has no handler for the form.
NOT_IMPLEMENTED = "not-implemented"
# The handler exists but refused a parameterless read (`invalid proto_name`, `invalid parameter
# vpntype`), so it is reachable once the right argument is supplied.
NEEDS_PARAMETERS = "exists-needs-parameters"
# The CGI answered with a file or a server error instead of the JSON envelope.
NON_JSON = "non-json-or-server-error"
# The router served HTTP 404 for this module: the UI references it, this device does not host it.
NOT_SERVED = "not-served-404"
# Deliberately not probed: the form name is itself an action (`reboot`, `logout`, `cloud_upgrade`).
NOT_PROBED = "not-probed"

READ_VERBS = ("read", "load", "list")


@dataclass(frozen=True)
class Endpoint:
    """One `module?form=` pair, as the UI builds it and as this firmware answered it."""

    module: str
    form: str
    ui_operations: tuple[str, ...]
    read_verbs: tuple[str, ...] = ()
    status: str = NOT_PROBED
    others_key: str | None = None
    row_fields: tuple[str, ...] = ()
    #: False when no bundle names this form and only this package addresses it.
    in_bundles: bool = True

    @property
    def url(self) -> str:
        """The path the SDK passes to `ArcherAX12.read`/`write`/`api`."""
        return f"{self.module}?form={self.form}"

    @property
    def is_row_form(self) -> bool:
        """True when the form is a list of records rather than a settings blob.

        Empty tables answer `{}`, not `[]`, so a row form has to be recognised from its `others`
        sibling as well as from an array payload.
        """
        return bool(self.row_fields) or self.others_key is not None


def _e(module: str, form: str, ui: tuple[str, ...], read: tuple[str, ...], status: str,
       others: str | None = None, fields: tuple[str, ...] = (), in_bundles: bool = True) -> Endpoint:
    return Endpoint(module, form, ui, read, status, others, fields, in_bundles)


ENDPOINTS: tuple[Endpoint, ...] = (
    # /accessibility
    _e("accessibility", "accessibility_state", ('read', 'write'), ('read',), ANSWERED),

    # /admin/access_control
    _e("admin/access_control", "black_devices",
        ('block', 'load', 'request'), ('load',), ANSWERED, fields=('conn_type', 'guest', 'host',
                         'ipaddr', 'mac', 'name', 'raw_conn_type', 'type')),
    _e("admin/access_control", "black_list", ('insert', 'load', 'remove'), ('load',), ANSWERED, others='max_rules'),
    _e("admin/access_control", "enable", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/access_control", "mode", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/access_control", "white_devices",
        ('access', 'load', 'request'), ('load',), ANSWERED, fields=('conn_type', 'guest', 'host',
                         'ipaddr', 'mac', 'name', 'raw_conn_type', 'type')),
    _e("admin/access_control", "white_list", ('insert', 'load', 'remove'), ('load',), ANSWERED, others='max_rules'),

    # /admin/administration
    _e("admin/administration", "account", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/administration", "https", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/administration", "local", ('insert', 'load', 'remove'), ('load',), ANSWERED, others='max_rules'),
    _e("admin/administration", "mode", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/administration", "recovery", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/administration", "remote", ('read', 'write'), ('read',), ANSWERED),

    # /admin/cloud_account
    _e("admin/cloud_account", "auto_update_remind", ('read',), (), NEEDS_PARAMETERS),
    _e("admin/cloud_account", "check_device", ('read',), ('read',), ANSWERED),
    _e("admin/cloud_account", "check_internet", ('read',), ('read',), ANSWERED),
    _e("admin/cloud_account", "check_upgrade", ('read',), ('read',), ANSWERED),
    _e("admin/cloud_account", "cloud_bind_status", ('read', 'request'), ('read',), ANSWERED),
    _e("admin/cloud_account", "cloud_unbind", ('write',), (), NOT_IMPLEMENTED),
    _e("admin/cloud_account", "cloud_upgrade", ('read', 'request', 'upgrade'), (), NOT_PROBED),
    _e("admin/cloud_account", "detect_upgrade_status", ('read',), (), NEEDS_PARAMETERS),
    _e("admin/cloud_account", "get_device", ('read',), (), NOT_IMPLEMENTED),
    _e("admin/cloud_account", "get_token", ('read',), ('read',), ANSWERED),
    _e("admin/cloud_account", "remind", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/cloud_account", "user_login", ('write',), ('read',), ANSWERED),

    # /admin/cwmp
    _e("admin/cwmp", "cwmp_setting", ('read', 'write'), ('read',), ANSWERED),

    # /admin/ddns
    _e("admin/ddns", "dyndns", ('login', 'logout', 'read', 'refresh', 'request'), ('read',), ANSWERED),
    _e("admin/ddns", "noip", ('login', 'logout', 'read', 'refresh', 'request'), ('read',), ANSWERED),
    _e("admin/ddns", "provider", ('read',), ('read',), ANSWERED),
    _e("admin/ddns", "tplink", ('bind', 'insert', 'load', 'remove', 'request', 'unbind'), ('load',), ANSWERED),

    # /admin/dhcps
    _e("admin/dhcps", "client", ('load',), ('load',), ANSWERED, fields=('ipaddr', 'leasetime', 'macaddr', 'name')),
    _e("admin/dhcps", "reservation",
        ('insert', 'load', 'remove', 'update'), ('load',), ANSWERED, others='max_rules',
                         fields=('comment', 'enable', 'hostname', 'ip', 'mac')),
    _e("admin/dhcps", "setting", ('read', 'write'), ('read',), ANSWERED),

    # /admin/diag
    _e("admin/diag", "diag", ('continue', 'request', 'start', 'stop'), ('read',), ANSWERED),

    # /admin/easymesh
    _e("admin/easymesh", "easymesh_enable", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/easymesh", "search_slave", ('check', 'request', 'start', 'stop'), (), NOT_PROBED),

    # /admin/easymesh_network
    _e("admin/easymesh_network", "ap_avoidance_enable_status", ('read',), ('read',), ANSWERED),
    _e("admin/easymesh_network", "available_mesh_device_manage",
        ('add_onboarding', 'link', 'request', 'unlink'), (), NOT_IMPLEMENTED),
    _e("admin/easymesh_network", "change_satellite", ('write',), (), NOT_IMPLEMENTED),
    _e("admin/easymesh_network", "mesh_sclient_detail", ('read', 'request', 'write'), (), NON_JSON),
    _e("admin/easymesh_network", "mesh_sclient_list_all", ('read',), ('read',), ANSWERED),

    # /admin/ffs
    _e("admin/ffs", "config", ('read', 'write'), ('read',), ANSWERED),

    # /admin/firmware
    _e("admin/firmware", "auto_upgrade", ('read', 'write'), (), NOT_PROBED),
    _e("admin/firmware", "config", ('check', 'factory', 'read', 'request'), ('read',), ANSWERED),
    _e("admin/firmware", "config_multipart", ('backup', 'file', 'restore'), (), NOT_PROBED),
    _e("admin/firmware", "save_upgrade", ('file', 'firmware'), (), NOT_PROBED),
    _e("admin/firmware", "slave_cmd",
        ('request', 'slave_get_info', 'slave_get_upgrade_info', 'slave_upgrade_firmware'), (),
                         NOT_PROBED),
    _e("admin/firmware", "upgrade", ('fwup_check', 'read', 'request', 'write'), (), NOT_PROBED),

    # /admin/imb
    _e("admin/imb", "arp_list",
        ('bind', 'load', 'remove', 'request'), ('load',), ANSWERED, others='max_rules',
                         fields=('enable', 'ipaddr', 'mac', 'name')),
    _e("admin/imb", "bind_list", ('insert', 'load', 'remove'), ('load',), ANSWERED, others='max_rules'),
    _e("admin/imb", "client_list",
        ('read',), ('read',), ANSWERED, fields=('client_type', 'guest', 'ip', 'mac', 'name',
                         'wire_type')),
    _e("admin/imb", "setting", ('read', 'write'), ('read',), ANSWERED),

    # /admin/iptv
    _e("admin/iptv", "setting", ('change', 'read', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/iptv", "udp_proxy_setting", ('read', 'write'), ('read',), ANSWERED),

    # /admin/l2tpoveripsec
    _e("admin/l2tpoveripsec", "config", ('read',), ('read',), ANSWERED),

    # /admin/ledgeneral
    _e("admin/ledgeneral", "setting", ('read', 'write'), ('read',), ANSWERED),

    # /admin/ledpm
    _e("admin/ledpm", "setting", ('read', 'write'), ('read',), ANSWERED),

    # /admin/nat
    _e("admin/nat", "alg", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/nat", "client_list",
        ('read',), ('read',), ANSWERED, fields=('client_type', 'guest', 'ip', 'mac', 'name',
                         'wire_type')),
    _e("admin/nat", "client_list_v6", ('read',), ('read',), ANSWERED),
    _e("admin/nat", "dmz", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/nat", "fr6", ('insert', 'load', 'remove', 'update'), ('load', 'read'), ANSWERED),
    _e("admin/nat", "pt", ('insert', 'load', 'remove', 'update'), ('load', 'read'), ANSWERED, others='max_rules'),
    _e("admin/nat", "setting", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/nat", "vs", ('insert', 'load', 'remove', 'update'), ('load', 'read'), ANSWERED, others='max_rules'),

    # /admin/network
    _e("admin/network", "lan_agg", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "lan_fc", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "lan_ipv4", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "lan_ipv6", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "mac_clone_advanced", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "port_speed_current", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "port_speed_supported", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/network", "routes_static",
        ('insert', 'load', 'remove', 'update'), ('load',), ANSWERED, others='max_rules'),
    _e("admin/network", "routes_system",
        ('load',), ('load',), ANSWERED, fields=('dest', 'gateway', 'interface', 'mask')),
    _e("admin/network", "status_ipv4", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/network", "wan_autodetect", ('detect', 'read', 'request'), (), NEEDS_PARAMETERS),
    _e("admin/network", "wan_fc", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_bigpond", ('read', 'write'), (), NEEDS_PARAMETERS),
    _e("admin/network", "wan_ipv4_dslite", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_dynamic", ('read', 'release', 'renew', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_l2tp", ('connect', 'disconnect', 'read', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_ocn", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_pppoe",
        ('connect', 'disconnect', 'read', 'release', 'renew', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_pptp", ('connect', 'disconnect', 'read', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_protos", ('read', 'request'), ('read',), ANSWERED, fields=('name', 'value')),
    _e("admin/network", "wan_ipv4_staticip", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_status", ('read',), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv4_v6plus", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv6_dynamic", ('read', 'release', 'renew', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv6_pass", ('write',), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv6_pppoe", ('connect', 'disconnect', 'read', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv6_protos", ('read', 'request'), ('read',), ANSWERED, fields=('name', 'value')),
    _e("admin/network", "wan_ipv6_static", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv6_status", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_ipv6_tunnel",
        ('connect', 'disconnect', 'read', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_port_status", ('detect', 'read', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/network", "wan_retrieve_ipv4_pppoe", ('read', 'write'), ('read',), ANSWERED),

    # /admin/openvpn
    _e("admin/openvpn", "config", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/openvpn", "export", ('backup', 'file'), (), NON_JSON),
    _e("admin/openvpn", "openvpn_cert", ('check', 'generate', 'request'), (), NOT_PROBED),

    # /admin/pptpd
    _e("admin/pptpd", "accounts", ('insert', 'load', 'remove', 'update'), ('load',), ANSWERED, others='max_accounts'),
    _e("admin/pptpd", "config", ('read', 'write'), ('read',), ANSWERED),

    # /admin/privacy_policy
    _e("admin/privacy_policy", "fing_auth_state", ('read', 'write'), ('read',), ANSWERED),

    # /admin/qos
    _e("admin/qos", "update_database", (), ('read',), ANSWERED),

    # /admin/quick_setup
    _e("admin/quick_setup", "ap_setup", ('read', 'write'), (), NOT_PROBED),
    _e("admin/quick_setup", "check_router", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/quick_setup", "quick_setup", ('read', 'write'), (), NOT_PROBED),

    # /admin/reboot
    _e("admin/reboot", "set", ('read', 'write'), ('read',), ANSWERED),

    # /admin/security_settings
    _e("admin/security_settings", "new_enable", ('read', 'write'), ('read',), ANSWERED),

    # /admin/smart_network
    _e("admin/smart_network", "client_speed_limit", ('read_max', 'request', 'write'), (), NOT_IMPLEMENTED),
    _e("admin/smart_network", "device_priority",
        ('load', 'update'), ('load',), ANSWERED, fields=('deviceName', 'deviceTag', 'deviceType',
                         'downloadSpeed', 'enablePriority', 'index', 'key', 'mac', 'remainTime',
                         'timePeriod', 'time_mode', 'trafficUsage', 'uploadSpeed')),
    _e("admin/smart_network", "game_accelerator", ('request',), (), NOT_IMPLEMENTED),
    _e("admin/smart_network", "get_host_info", ('read',), ('read',), ANSWERED),
    _e("admin/smart_network", "patrol_devices",
        ('load',), ('load', 'list', 'read'), ANSWERED, fields=('client_type', 'device_id', 'mac',
                         'name', 'online', 'owner_id', 'prio', 'prio_time', 'time_period')),
    _e("admin/smart_network", "patrol_enable", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/smart_network", "patrol_insights", ('read', 'request'), (), NEEDS_PARAMETERS),
    _e("admin/smart_network", "patrol_limit", ('read',), ('read',), ANSWERED),
    _e("admin/smart_network", "patrol_owner_block", ('write',), (), NOT_IMPLEMENTED),
    _e("admin/smart_network", "patrol_owner_list",
        ('insert', 'load', 'remove', 'update'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/smart_network", "patrol_owner_website_block", ('write',), (), NOT_IMPLEMENTED),
    _e("admin/smart_network", "qos", ('read', 'write'), ('read',), ANSWERED),

    # /admin/status
    _e("admin/status", "all", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/status", "cloud_login_window_pop", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/status", "internet", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/status", "menu_status", ('read', 'request', 'set'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/status", "router",
        ('read',), ('read',), ANSWERED, fields=('duplex', 'is_wan', 'name', 'speed', 'status')),
    _e("admin/status", "speedtest",
        ('clear', 'get', 'get_servers', 'get_status', 'modify_status', 'read', 'request', 'start',
                         'stop'), (), NON_JSON),
    _e("admin/status", "user_experience_plan_switch", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/status", "wan_cable_match_stat", ('read_match', 'request'), (), NOT_IMPLEMENTED),
    _e("admin/status", "wan_dual_nat_state", ('read',), ('read',), ANSWERED),
    _e("admin/status", "wan_speed", ('read',), ('load', 'list', 'read'), ANSWERED),

    # /admin/syslog
    _e("admin/syslog", "filter", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/syslog", "log", ('load', 'mail', 'remove', 'request'), ('load',), ANSWERED),
    _e("admin/syslog", "mail", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/syslog", "save_log", ('file', 'save'), (), NOT_PROBED),
    _e("admin/syslog", "types", ('load',), ('load', 'list', 'read'), ANSWERED, fields=('name', 'value')),

    # /admin/system
    _e("admin/system", "logout", ('request',), (), NOT_PROBED),
    _e("admin/system", "reboot", ('reboot', 'request', 'write'), (), NOT_PROBED),
    _e("admin/system", "sysmode", ('read', 'write'), ('read',), ANSWERED),

    # /admin/time
    _e("admin/time", "dst", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/time", "hour24", ('write',), ('read',), ANSWERED),
    _e("admin/time", "settings", ('gmt', 'read', 'refresh', 'request', 'write'), ('read',), ANSWERED),

    # /admin/traffic
    _e("admin/traffic", "dev_name",
        ('write',), ('read',), ANSWERED, fields=('access_time', 'access_uptime', 'connect_device_id',
                         'connect_device_mac', 'connect_status', 'device_type', 'guest', 'hostname',
                         'ip', 'mac', 'name', 'wire_type')),

    # /admin/upnp
    _e("admin/upnp", "enable", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/upnp", "service", ('load',), ('load', 'list', 'read'), ANSWERED),

    # /admin/usbmodem
    _e("admin/usbmodem", "isplist", ('read',), ('read',), ANSWERED),
    _e("admin/usbmodem", "modemset", ('read',), ('read',), ANSWERED),

    # /admin/vpn
    _e("admin/vpn", "enable", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/vpn", "ovpn", ('file', 'read', 'release', 'request', 'write'), ('read',), ANSWERED),
    _e("admin/vpn", "server",
        ('connected_status', 'file_check', 'insert', 'load', 'remove', 'request', 'update'), ('load',),
                         ANSWERED, others='max_rules'),
    _e("admin/vpn", "thirdvpn",
        ('cloud_check', 'enable_server', 'get_detail', 'get_ping', 'get_server_list', 'insert',
                         'modify', 'nordvpn_login', 'request', 'surfshark_login', 'update',
                         'update_config', 'verify'), (), NOT_IMPLEMENTED),
    _e("admin/vpn", "vpn_user_devices",
        ('load',), ('load', 'list', 'read'), ANSWERED, fields=('client_type', 'device_id', 'mac',
                         'name', 'online', 'owner_id', 'prio', 'prio_time', 'time_period')),
    _e("admin/vpn", "vpn_user_list", ('insert', 'load', 'remove', 'request', 'update'), ('load',), ANSWERED),
    _e("admin/vpn", "wireguard", ('file', 'upload_file'), (), NEEDS_PARAMETERS),

    # /admin/vpnconn
    _e("admin/vpnconn", "config", ('disconnect', 'list', 'request'), (), NEEDS_PARAMETERS),

    # /admin/wifidog
    _e("admin/wifidog", "portal_background", ('file', 'read', 'upload'), ('read',), ANSWERED),
    _e("admin/wifidog", "portal_logo", ('file', 'read', 'upload'), ('read',), ANSWERED),

    # /admin/wireguard
    _e("admin/wireguard", "account",
        ('check_collision', 'download', 'export', 'file', 'get_default', 'insert', 'load', 'remove',
                         'renew', 'request', 'update'), ('load',), ANSWERED, others='max_clients'),
    _e("admin/wireguard", "config", ('read', 'renew', 'request', 'wg_status', 'write'), ('read',), ANSWERED),

    # /admin/wireless
    _e("admin/wireless", "guest", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "guest_2g", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "guest_2g5g", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "guest_5g", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "guest_5g_2", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "guest_6g", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "guestnetwork_bandwidth_ctrl", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/wireless", "guestnetwork_effectivetime_ctrl", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/wireless", "iot_2g", ('read_spf', 'request', 'write_spf'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "iot_5g", ('read_spf', 'request', 'write_spf'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "iot_5g_2", ('read_spf', 'request', 'write_spf'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "mlo_host", ('read', 'write'), (), NOT_IMPLEMENTED),
    _e("admin/wireless", "ofdma", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "ofdma_mimo", ('read', 'write'), (), NOT_IMPLEMENTED),
    _e("admin/wireless", "portal_content", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "region", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "smart_connect", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "statistics",
        (), ('load', 'list', 'read'), ANSWERED, fields=('encryption', 'mac', 'rxpkts', 'txpkts',
                         'type'), in_bundles=False),
    _e("admin/wireless", "syspara_2g", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "syspara_5g", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "syspara_5g_2", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "syspara_6g", ('read',), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "syspara_wps", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "twt", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "wireless", (), (), NOT_IMPLEMENTED),
    _e("admin/wireless", "wireless_2g", ('read', 'read_spf', 'request'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "wireless_5g", ('read', 'read_spf', 'request'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "wireless_5g_2", ('read', 'read_spf', 'request'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "wireless_6g", ('read_spf', 'request'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "wireless_addition_setting", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/wireless", "wireless_schedule", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/wireless", "wps_connect", ('read', 'request'), ('load', 'list', 'read'), ANSWERED),
    _e("admin/wireless", "wps_pin", ('read', 'write'), ('load', 'list', 'read'), ANSWERED),

    # /admin/wol
    _e("admin/wol", "device",
        ('insert', 'load', 'remove', 'request', 'update', 'wakeup'), ('load',), ANSWERED,
                         others='max_rules'),

    # /admin/yandex_dns
    _e("admin/yandex_dns", "device", ('insert', 'load', 'remove', 'update'), ('load',), ANSWERED, others='max_rules'),
    _e("admin/yandex_dns", "enable", ('read', 'write'), ('read',), ANSWERED),
    _e("admin/yandex_dns", "setting", ('read', 'write'), ('read',), ANSWERED),

    # /blocking
    _e("blocking", "vercode", (), (), NOT_SERVED),

    # /debug
    _e("debug", "cmd", (), (), NOT_SERVED),
    _e("debug", "refresh", (), (), NOT_SERVED),
    _e("debug", "upload", (), (), NOT_SERVED),

    # /device_config
    _e("device_config", "config", ('read',), ('read',), ANSWERED),

    # /domain_login
    _e("domain_login", "dlogin", ('read',), ('read',), ANSWERED),

    # /domain_redirect
    _e("domain_redirect", "get", (), ('load', 'list', 'read'), ANSWERED),

    # /locale
    _e("locale", "country", ('read',), ('read',), ANSWERED),
    _e("locale", "lang", ('read', 'write'), ('read',), ANSWERED),
    _e("locale", "list", ('read',), ('read',), ANSWERED, fields=('name', 'value')),
    _e("locale", "multilang", (), (), NOT_IMPLEMENTED),

    # /login
    _e("login", "auth", ('read',), ('read',), ANSWERED),
    _e("login", "check_factory_default", ('read',), ('read',), ANSWERED),
    _e("login", "check_internet", ('read',), ('read',), ANSWERED),
    _e("login", "cloud_bind_status", ('read',), ('read',), ANSWERED),
    _e("login", "cloud_login", ('write',), ('read',), ANSWERED),
    _e("login", "get_device", (), (), NOT_IMPLEMENTED),
    _e("login", "get_eweb_url", ('read',), ('read',), ANSWERED),
    _e("login", "get_firmware_info", (), ('load', 'list', 'read'), ANSWERED),
    _e("login", "get_logo_url", ('read',), ('read',), ANSWERED),
    _e("login", "get_token", (), (), NOT_IMPLEMENTED),
    _e("login", "keys", ('read',), ('read',), ANSWERED),
    _e("login", "password", (), ('read',), ANSWERED),
    _e("login", "sysmode", (), ('load', 'list', 'read'), ANSWERED),
    _e("login", "telemetry", ('request', 'user_action'), (), NOT_IMPLEMENTED),
    _e("login", "vercode", (), (), NEEDS_PARAMETERS),

    # /upgrade
    _e("upgrade", "info", (), ('read',), ANSWERED),
    _e("upgrade", "set", (), ('read',), ANSWERED),

    # /wan_error
    _e("wan_error", "never", (), (), NOT_IMPLEMENTED),
    _e("wan_error", "read", (), (), NON_JSON),
)

#: Every form under a module, e.g. ``MODULES["admin/nat"]``.
MODULES: dict[str, tuple[str, ...]] = {
    _module: tuple(sorted(_names))
    for _module, _names in (
        (_module, {endpoint.form for endpoint in ENDPOINTS if endpoint.module == _module})
        for _module in sorted({endpoint.module for endpoint in ENDPOINTS})
    )
}

#: `module?form=x` -> endpoint, for call sites that already hold a URL string.
BY_URL: dict[str, Endpoint] = {endpoint.url: endpoint for endpoint in ENDPOINTS}

MODULE_COUNT = len(MODULES)
FORM_COUNT = len(ENDPOINTS)
ANSWERED_COUNT = sum(1 for endpoint in ENDPOINTS if endpoint.status == ANSWERED)


def endpoint(module: str, form: str) -> Endpoint | None:
    """Look one endpoint up by module and form, with or without a leading slash."""
    return BY_URL.get(f"{module.lstrip('/')}?form={form.lstrip('/')}")


def forms(module: str) -> tuple[str, ...]:
    """Every inventoried form on a module."""
    return MODULES.get(module.lstrip("/"), ())


def answered_forms(module: str) -> tuple[str, ...]:
    """Forms this firmware actually answers with read, load or list."""
    return tuple(
        name
        for name in forms(module)
        if (entry := endpoint(module, name)) is not None and entry.status == ANSWERED
    )
