import json

from tplink_modern.exceptions import NotFoundError
from tplink_modern.models import WolDevice
from tplink_modern.resources.base import BaseResource

PATH = "admin/wol?form=device"


def _mac_key(macaddr: str) -> str:
    return macaddr.replace(":", "-").upper()


class WakeOnLanResource(BaseResource):
    """Saved Wake-on-LAN targets. The router stores them itself; it does not infer them."""

    async def devices(self) -> list[WolDevice]:
        """Devices the router has saved for waking, plus its own rule limit."""
        resp = await self.client.api("admin/wol", "device", "load")
        rows = resp.get("data") or []
        if isinstance(rows, dict):
            rows = list(rows.values())
        return [
            WolDevice.from_router(row, index=i)
            for i, row in enumerate(row for row in rows if isinstance(row, dict))
        ]

    async def max_rules(self) -> int | None:
        """How many entries the firmware allows, when it reports one."""
        resp = await self.client.api("admin/wol", "device", "load")
        others = resp.get("others")
        if isinstance(others, dict) and "max_rules" in others:
            return int(others["max_rules"])
        return None

    async def add(self, macaddr: str, name: str = "") -> bool:
        """Save a wake target. `key` is generated by the caller on this firmware."""
        await self.client.api(
            "admin/wol", "device", "insert",
            key=_mac_key(macaddr).replace("-", "").lower(),
            name=name,
            mac=_mac_key(macaddr),
            index=0,
        )
        return True

    async def remove(self, macaddr: str) -> bool:
        """Delete a saved wake target by MAC."""
        device = await self._find(macaddr)
        await self.client.api(
            "admin/wol", "device", "remove",
            key=device.key,
            index=device.index,
        )
        return True

    async def wake(self, macaddr: str | None = None, name: str | None = None) -> bool:
        """Send a magic packet to a saved device, by MAC or by name."""
        if macaddr is None and name is None:
            raise ValueError("wake needs a macaddr or a name")

        devices = await self.devices()
        for device in devices:
            if (macaddr and device.macaddr == _mac_key(macaddr)) or (name and device.name == name):
                row = dict(device.raw)
                row.setdefault("key", device.key)
                await self.client.api(
                    "admin/wol", "device", "wakeup",
                    data=json.dumps(row),
                )
                return True

        wanted = macaddr or name
        raise NotFoundError(f"{wanted} is not a saved Wake-on-LAN device; add it first")

    async def _find(self, macaddr: str) -> WolDevice:
        target = _mac_key(macaddr)
        for device in await self.devices():
            if device.macaddr == target:
                return device
        raise NotFoundError(f"{target} is not a saved Wake-on-LAN device")
